version: '2'
services:
  7dbtest-app:
    image: 7degrees
    depends_on:
      - 7degrees-mariadb
      - 7degrees-redis
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev
      - "MOVIE_DB_API_KEY=${MOVIE_DB_API_KEY}"
  7degrees-mariadb:
    image: mariadb:10.3.7
    volumes:
      - ~/volumes/7degrees/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=7degrees
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  7degrees-redis:
    tty: true
    image: redis:latest
    command: redis-server --requirepass 73656775726f64656e74616c6c6973616e65636573697461756e6170617261746f
    ports:
      - "6378:6379"
    environment:
      - pass=73656775726f64656e74616c6c6973616e65636573697461756e6170617261746f